# Generated by Django 5.2.7 on 2025-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remetente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_remetente', models.CharField(choices=[('Pessoa Física', 'Pessoa Física'), ('Pessoa Jurídica', 'Pessoa Jurídica'), ('Órgão Público', 'Órgão Público')], max_length=50, verbose_name='Tipo de Remetente')),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF / CNPJ')),
                ('contato', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato (E-mail/Telefone)')),
            ],
            options={
                'verbose_name': 'Remetente',
                'verbose_name_plural': 'Remetentes',
            },
        ),
    ]
