# Generated by Django 5.2.7 on 2025-10-14 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remetente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=50, unique=True, verbose_name='Protocolo')),
                ('status', models.CharField(choices=[('Aguardando Distribuição', 'Aguardando Distribuição'), ('Em Análise', 'Em Análise'), ('Análise Concluída', 'Análise Concluída'), ('Devolvido pela Análise', 'Devolvido pela Análise'), ('Finalizado', 'Finalizado')], default='Aguardando Distribuição', max_length=50)),
                ('num_doc_origem', models.CharField(max_length=100, verbose_name='Número do Doc. de Origem')),
                ('data_doc_origem', models.DateField(verbose_name='Data do Doc. de Origem')),
                ('observacoes_protocolo', models.TextField(blank=True, null=True, verbose_name='Observações do Protocolo')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Recebimento')),
                ('data_atribuicao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atribuição')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('obs_finalizacao', models.TextField(blank=True, null=True, verbose_name='Observações da Finalização')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.nivelprioridade', verbose_name='Prioridade')),
                ('procurador_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Procurador Atribuído')),
                ('protocolado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_protocolados', to=settings.AUTH_USER_MODEL, verbose_name='Protocolado por')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.remetente', verbose_name='Remetente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
