# Generated by Django 5.2.7 on 2025-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Data Limite para Resposta'),
        ),
        migrations.AddField(
            model_name='nivelprioridade',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=15, verbose_name='Prazo (em dias)'),
        ),
    ]
