# Generated by Django 5.2.7 on 2025-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_documento_data_limite_nivelprioridade_prazo_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_resposta_procurador',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta do Procurador'),
        ),
    ]
