# Generated by Django 5.2.7 on 2025-10-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_documento_finalizado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remetente',
            name='contato',
        ),
        migrations.AddField(
            model_name='remetente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='remetente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
