# Generated by Django 5.2.7 on 2025-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_remove_remetente_contato_remetente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('Aguardando Distribuição', 'Aguardando Distribuição'), ('Em Análise', 'Em Análise'), ('Análise Concluída', 'Análise Concluída'), ('Aguardando Confirmação', 'Aguardando Confirmação'), ('Devolvido pela Análise', 'Devolvido pela Análise'), ('Finalizado', 'Finalizado')], default='Aguardando Distribuição', max_length=50),
        ),
    ]
