# Generated by Django 5.2.7 on 2025-10-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_documento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='motivo_ultima_devolucao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Última Devolução'),
        ),
    ]
