# Generated by Django 5.2.7 on 2025-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_documento_motivo_ultima_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='motivo_ultima_reativacao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Última Reativação'),
        ),
    ]
