# Generated by Django 5.2.7 on 2025-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='motivo_rejeicao_analista',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição (Analista)'),
        ),
    ]
