# Generated by Django 5.2.7 on 2025-11-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_alter_anexo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
