# Generated by Django 5.2.7 on 2026-01-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0015_anexo_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="interessados",
            field=models.ManyToManyField(
                blank=True,
                related_name="processos_interessados",
                to="gestao.remetente",
                verbose_name="Interessados / Secretarias",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="notificar_remetente",
            field=models.BooleanField(default=False, verbose_name="Notificar Remetente na Finalização?"),
        ),
    ]
