# Generated by Django 5.2.7 on 2026-01-28 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0017_historicoedicao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoDocumento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao_necessidade", models.TextField(help_text="Explique quais documentos faltam.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente de Análise"),
                            ("Enviada", "E-mail enviado ao Remetente"),
                            ("Atendida", "Documento anexado / Concluída"),
                            ("Rejeitada", "Solicitação Negada pela Chefia"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                ("observacao_chefia", models.TextField(blank=True, null=True)),
                ("data_resposta", models.DateTimeField(blank=True, null=True)),
                (
                    "analisado_por",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="solicitacoes", to="gestao.documento"
                    ),
                ),
                (
                    "procurador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minhas_solicitacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
