# Generated by Django 5.2.7 on 2026-01-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0018_solicitacaodocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexo",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
